
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.3.0

project_structure:
  build: brownie/build
  contracts: brownie/contracts
  interfaces: brownie/interfaces
  reports: brownie/reports
  scripts: brownie/scripts
  tests: brownie/tests

networks:
  default: development
  development:
    gas_limit: max
    gas_price: auto
    reverting_tx_gas_limit: max
    default_contract_owner: true
  live:
    gas_limit: auto
    gas_price: auto
    reverting_tx_gas_limit: false
    default_contract_owner: false

compiler:
  evm_version: null
  solc:
    version: 0.6.12
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.3.0"
console:
  show_colors: true
  color_style: monokai
  auto_suggest: true
  completions: true

reports:
  exclude_paths: null
  exclude_contracts: null

hypothesis:
  deadline: null
  max_examples: 50
  report_multiple_bugs: False
  stateful_step_count: 10
  phases:
    explicit: true
    reuse: true
    generate: true
    target: true
    shrink: true

dev_deployment_artifacts: false

# automatically fetch contract sources from Etherscan
autofetch_sources: True
